### ISSUE TITLE
sort out domain problem with IWantMyName

### ISSUE THREAD

**Issue by whit537** [flybottles/flybottl.es#2]
There's an error on the manage page.

**Comment by whit537** [comment]
> Thanks for getting in touch. We have been alerted about an issue with your order and will have to look into it more closely. The .ES registry changed their registration policies recently and the issue is most likely related to that. We’ll let you know when the domain has been registered or if we need any additional information as soon as possible.

**Comment by whit537** [comment]
Might need an alternative. :-/

**Comment by bayprogrammer** [comment]
Doesn't have the appeal of spelling part of the word using the TLD, but what about registering flybottles.com and/or flybottles.net as an alternative, at least until things get sorted with te .es TLD?

**Comment by whit537** [comment]
@bayprogrammer Thankfully, we're all sorted! :dancer: 

http://flybottl.es/

P.S. My son says, "His beard is so fluffy! It's like, 'floof'." :bear:

**Comment by bayprogrammer** [comment]
LOL. Big bushy beards FTW!!
